server:
  port: 1616
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1313/eureka/
spring:
  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/ronakdb
     username: root
     password: root
  jpa:
     hibernate.ddl-auto: update
     hibernate.show-sql: true
  properties:
     hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
  application:
     name: ORDER-SERVICE